Registration task
ClevertecFrontendLab/Irina05-04 pull request #3
Opened 2023-03-06 14:06 UTC by Irina05-04

1. Sprint 5
2. 06.03/13.03
3. 20/20

2023-03-06 22:32 UTC, SergeyGlazun requested changes

2023-03-06 22:32 UTC, SergeyGlazun commented on package.json
>      "react": "^18.2.0",
![image](https://user-images.githubusercontent.com/70904466/223257970-e677351e-e7ff-43e3-9a5e-939cb58cff86.png)
тесты не прохоят возможно из за того что отрабатывают раньше чем приходят данные, попробуй обработки в useEfect обернуть

2023-03-06 22:32 UTC, SergeyGlazun commented on src/index.js
> +      {/* <Header/>
кометы нужно удалять когда на заливку шлете

2023-03-06 22:32 UTC, SergeyGlazun commented on src/index.js
> +      {/* </main>
и тут тоже, на практики оч редко когда помогают

2023-03-06 22:32 UTC, SergeyGlazun commented on src/pages/registration/registration.scss
> +        margin-top: 3.2rem;
rem в марджинах на практики тож не видел лучше в px

2023-03-06 22:32 UTC, SergeyGlazun commented on src/pages/registration/registration.tsx
> +                            value: /(?:\+375)\s?\(?\d\d\)?\s?\d\d(?:\d[\\-\s]\d\d[\\-\s]\d\d|[\\-\s]\d\d[\\-\s]\d\d\d|\d{5})/,
патерны в отдельный файлик над как константы

2023-03-06 22:32 UTC, SergeyGlazun commented on src/pages/registration/registration.tsx
> +                        value: /^([a-z0-9_-]+\.)*[a-z0-9_-]+@[a-z0-9_-]+(\.[a-z0-9_-]+)*\.[a-z]{2,6}$/,
и тут тоже

2023-03-09 06:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 20.
Количество непройденных тестов: 1.
***
**authorization and registartion -- password recovery -- forgot password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/authorization%20and%20registartion%20--%20password%20recovery%20--%20forgot%20password%20validation%20(failed).png)
***
**error reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/error%20reset%20password.png)
***
**first enter.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/first%20enter.png)
***
**incorrect logit or password error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/incorrect%20logit%20or%20password%20error.png)
***
**loader authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/loader%20authorization.png)
***
**password hidden.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/password%20hidden.png)
***
**password shown.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/password%20shown.png)
***
**recovery page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/recovery%20page.png)
***
**registration already used error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/registration%20already%20used%20error.png)
***
**registration error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/registration%20error.png)
***
**registration page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/registration%20page.png)
***
**registration-first-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/registration-first-step.png)
***
**registration-second-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/registration-second-step.png)
***
**registration-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/registration-success.png)
***
**registration-third-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/registration-third-step.png)
***
**send email error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/send%20email%20error.png)
***
**send email success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/send%20email%20success.png)
***
**server error authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/server%20error%20authorization.png)
***
**success reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1678342661/success%20reset%20password.png)

2023-03-09 06:39 UTC, merged