Sprint7
ClevertecFrontendLab/Irina05-04 pull request #5
Opened 2023-03-24 13:48 UTC by Irina05-04

Sprint7

2023-03-24 18:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 98.
Количество непройденных тестов: 7.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- category change -- active category should be design (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/Sprint%204%20--%20search%20and%20sort%20--%20category%20change%20--%20active%20category%20should%20be%20design%20(failed).png)
***
**Sprint 4 -- search and sort -- category change -- active category should be programming (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/Sprint%204%20--%20search%20and%20sort%20--%20category%20change%20--%20active%20category%20should%20be%20programming%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20validation%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- forgot password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20forgot%20password%20validation%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679681716/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-25 12:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 91%.
Общее количество тестов: 98.
Количество непройденных тестов: 8.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- category change -- active category should be programming (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%204%20--%20search%20and%20sort%20--%20category%20change%20--%20active%20category%20should%20be%20programming%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20validation%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- forgot password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20forgot%20password%20validation%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679747254/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-25 18:41 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 91%.
Общее количество тестов: 98.
Количество непройденных тестов: 8.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- category change -- active category is empty (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%204%20--%20search%20and%20sort%20--%20category%20change%20--%20active%20category%20is%20empty%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20validation%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- forgot password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20forgot%20password%20validation%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679769665/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-25 19:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/5-slider-after-1440px.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/Sprint%202%20--%20slider%20tests%20--%20test%20layout%20burger-menu%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- forgot password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20forgot%20password%20validation%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679770977/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-25 20:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 63.
Количество непройденных тестов: 5.
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/19-profile-avatar-after.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/25-1440-history.png)
***
**Sprint 5 -- authorization and registartion -- password recovery -- forgot password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/Sprint%205%20--%20authorization%20and%20registartion%20--%20password%20recovery%20--%20forgot%20password%20validation%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679775671/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-25 20:50 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/5-slider-after-1440px.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/Sprint%202%20--%20slider%20tests%20--%20test%20layout%20burger-menu%20(failed).png)
***
**Sprint 4 -- search and sort -- category change -- active category should be design (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/Sprint%204%20--%20search%20and%20sort%20--%20category%20change%20--%20active%20category%20should%20be%20design%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679777458/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-25 21:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/5-slider-after-1440px.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/Sprint%202%20--%20slider%20tests%20--%20test%20layout%20burger-menu%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679779174/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)

2023-03-26 00:24 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +    const user = useAppSelector(state => state.user.user);
Попробуй создать селекторы 
```
const { user } = useAppSelector(userSelector);

2023-03-26 00:24 UTC, ValadzkoAliaksei commented on src/components/button/button.scss
> +        background: rgba(0,0,0,0) !important;
что-то очень много везде important. Они должны использоваться крайне редко!!! или вообще никогда

2023-03-26 00:24 UTC, ValadzkoAliaksei commented on src/components/swiper/swiper.tsx
> +  interface HistorySliderProps{
интерфейсы в type

2023-03-26 00:24 UTC, ValadzkoAliaksei commented on src/function/date/compare-date.ts
> +export function CompareDate(date1: Date, date2: Date){
можно имена получше, чем date1 date2?

2023-03-26 00:24 UTC, ValadzkoAliaksei commented on src/pages/main/main-page.tsx
> +  const isErrorBooking = useAppSelector((state) => state.booking.error);
можно сделать 1 селектор и забрать все параметры деструктуризацией. Сэкономишь массу строк)

2023-03-26 00:24 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +      }, [isSuccessBooking.value]);
можно ли это как-нибудь инифицировать?
например прятать алерт внутри него, а не снаружи. и что бы он был 1 и зависел от 1 переменной

2023-03-26 00:24 UTC, ValadzkoAliaksei commented on src/redux/comment-slice.ts
> +export const { setError, hiddenLoading, showLoading, setSuccess, setModal, setCurrent } = CommentSlice.actions;
можно ли запросы вынести из слайса?

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +      useEffect(() => {
![image](https://user-images.githubusercontent.com/61273546/227748805-52023180-3ff8-4e54-800b-967f99ff05f9.png)
по клику мимо, выпадашка, должна прятаться

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +          const text = (userBook)?.text ?? ''
![image](https://user-images.githubusercontent.com/61273546/227748823-d09a2b3c-438c-47a4-87ae-cc39259bffce.png)
Выпадашка бессмертная, не прячется даже после перехода на страницу профиля

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +
![image](https://user-images.githubusercontent.com/61273546/227748852-0d6f612c-98db-4815-a349-745ca725ff08.png)
Если фотки нет, то должен быть котик

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +          setValue('text', text);
![image](https://user-images.githubusercontent.com/61273546/227748867-05e9646d-acc6-4d21-af77-d26a71e4fce7.png)
Можно отправить отзыв с пустым рейтингом, хорошо, что хоть на беке ошибка падает)

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +        }
![image](https://user-images.githubusercontent.com/61273546/227748902-181cb9ca-679d-43ec-b363-cc80cf7d5b37.png)
Если оценка уже есть, то должно быть - Изменить оценку

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +      }, [user])
![image](https://user-images.githubusercontent.com/61273546/227748984-2bedd624-3e42-4d3d-b398-03308e32d8c8.png)
Если книжек мало, то слайдера не должно быть

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +          const rat = userBook?.rating ?? 0;
![image](https://user-images.githubusercontent.com/61273546/227749050-985fb76c-5ddb-46b6-90f8-2987f2f8fdeb.png)
Можно выбрать выходной и получить ошибку

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +          const rat = userBook?.rating ?? 0;
и строка запроса кривая
Не должно быть слеша в ней

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +
![image](https://user-images.githubusercontent.com/61273546/227749089-5c284e1f-1757-4c9f-aa1c-e10959749215.png)
Что-то очень много запросов летит и  к месту и не к месту. Пересмотри все что не надо удали

2023-03-26 00:43 UTC, ValadzkoAliaksei commented on src/components/add-comment/add-coment.tsx
> +          setRating(rat);
![image](https://user-images.githubusercontent.com/61273546/227749123-c0efe2b2-aba0-4c8c-8fd0-0c2559b2ec88.png)
Просто открываю книгу по id и 6 запросов летит..
это ж явно перебор

2023-03-26 09:20 UTC, SergeyGlazun requested changes

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/book-card/book-card.scss
> +      // width: 82.5rem;
![image](https://user-images.githubusercontent.com/70904466/227765696-e51c8d59-8a5a-4b17-a3b7-601d5711da29.png)
анимация хорошо конечно но когда она без багов

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/book-card/book-card.scss
>        height: 21.8rem;
![image](https://user-images.githubusercontent.com/70904466/227765801-0921d0f8-8dc1-4f52-aeec-2763f6c37bef.png)
кривавато вышло немного

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/book-card/book-card.scss
>        column-gap: 1.6rem;
![image](https://user-images.githubusercontent.com/70904466/227765862-cdf49bf5-f78e-4cb9-b617-e6ed004bda9e.png)
а если нажал бы?) сохранился изменения то улител бы  не тот пароль

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/book-card/book-card.scss
> -      @media(max-width: 1150px){
![image](https://user-images.githubusercontent.com/70904466/227765932-e91706b3-e481-4fc3-96dd-33159dd4eac2.png)
когда переходим на страницу выпадашку над закрывать

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/delivery-section/delivery-profile.tsx
> +        {/* {user?.delivery.handed === null && (
удаляйте коменты

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/empty/empty.scss
> +    height: 21.8rem;
в длина высотах лучше % rem для шрифтов

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/email.tsx
> +    register: any,
тут определитесь с тип данных any оч плохо везде

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/email.tsx
> +        <input
нужно пере использовать компоненты тут можно было бы взять с регистрации input

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/login.tsx
> +          disabled={isActiveForm ? false: true}
и тут можно было бы переиспользовать

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/name.tsx
> +            placeholder=' '
а в чем смысл такого плейс холдера?)

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/password.tsx
> +            {' '}
странный чебурашка

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/password.tsx
> +          <input
и тут по идеи можно было бы пере использовать

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/phone.tsx
> +    // useEffect(() => {
коменты

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/phone.tsx
> +                  // setPhoneEmpty(true);
коменты

2023-03-26 09:20 UTC, SergeyGlazun commented on src/components/profile-info/phone.tsx
> +            В формате +375 (xx) xxx-xx-xx
тут 3 раза повторяеться можно было бы в константу вынести В формате +375 (xx) xxx-xx-xx

2023-03-26 09:50 UTC, Irina05-04 commented on src/components/book-card/book-card.scss
>        column-gap: 1.6rem;
нет, там стоит, если пароль не меняется, он не передается

2023-03-26 09:55 UTC, Irina05-04 commented on src/pages/main/main-page.tsx
> +  const isErrorBooking = useAppSelector((state) => state.booking.error);
можете ли объяснить как? не совсем поняла

2023-03-26 15:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/5-slider-after-1440px.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/Sprint%202%20--%20slider%20tests%20--%20test%20layout%20burger-menu%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- redirect authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679846007/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20redirect%20authorization%20(failed).png)

2023-03-26 16:21 UTC, SergeyGlazun requested changes

2023-03-26 16:21 UTC, SergeyGlazun commented on src/components/add-comment/add-coment.tsx
>  import { IReviewForm } from '../../models/form';
![Uploading image.png…]()
все тот же баг остался

2023-03-26 16:21 UTC, SergeyGlazun commented on src/components/add-comment/add-coment.tsx
>  import { IReviewForm } from '../../models/form';
![image](https://user-images.githubusercontent.com/70904466/227788863-3785d303-5d97-4ba3-989f-1e28d17bd616.png)

2023-03-26 16:21 UTC, SergeyGlazun commented on src/components/add-comment/add-coment.tsx
>  import { addComment, editComment } from '../../redux/comment-slice';
при невалидно пароле идет запрос 
![image](https://user-images.githubusercontent.com/70904466/227788902-59722ac0-0306-4f97-94c9-49202e7cf588.png)

2023-03-26 16:21 UTC, SergeyGlazun commented on src/components/add-comment/add-coment.tsx
> +import { authSelector, userSelector } from '../../redux/selector';
![image](https://user-images.githubusercontent.com/70904466/227789033-d4c3c006-a48e-4fef-96d0-9f288c0ce99b.png)
нет иконок

2023-03-26 16:21 UTC, SergeyGlazun commented on src/components/add-comment/add-coment.tsx
![image](https://user-images.githubusercontent.com/70904466/227789101-abe4c892-b006-4e8a-8da5-ee5c11c00c3d.png)
при редактировании не должно быть этого пароля

2023-03-26 16:21 UTC, SergeyGlazun commented on src/components/add-comment/add-coment.tsx
> -interface AddCommentProps{
![image](https://user-images.githubusercontent.com/70904466/227789434-d0a139fa-0375-4af4-ae33-f7d60b523f5d.png)
перезагрузка всей старницы тоже осталась

2023-03-26 16:21 UTC, SergeyGlazun commented on src/components/add-comment/add-coment.tsx
> +type AddCommentProps = {
![image](https://user-images.githubusercontent.com/70904466/227789476-dd6ff9dc-cb55-48f4-ac28-b0390c87469e.png)
много !important

2023-03-26 19:18 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- category change -- active category is empty (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/Sprint%204%20--%20search%20and%20sort%20--%20category%20change%20--%20active%20category%20is%20empty%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679858299/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 19:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- category change -- active category should be programming (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/Sprint%204%20--%20search%20and%20sort%20--%20category%20change%20--%20active%20category%20should%20be%20programming%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679859032/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 21:37 UTC, SergeyGlazun requested changes

2023-03-26 21:37 UTC, SergeyGlazun commented on src/redux/categories-slice.ts
>     isAmount: boolean;
![image](https://user-images.githubusercontent.com/70904466/227805391-9af4bf5c-9a3f-4e35-b259-ae41848a58e0.png)
не показывает ошибку на поле пароля и забыл пароль должно тольо по надписи рабоать и той области а не на весь блок

2023-03-26 21:37 UTC, SergeyGlazun commented on src/redux/categories-slice.ts
>  const initialState: CategoriesState = {
![image](https://user-images.githubusercontent.com/70904466/227805532-c9aa6f50-559d-4021-920e-86947764209c.png)
убирите глазик что б не вводить в  заблуждение. По нему можно кликнуть и там будет не тот пароль который у пользователя

2023-03-26 21:37 UTC, SergeyGlazun commented on src/redux/categories-slice.ts
>     categories: [],
![image](https://user-images.githubusercontent.com/70904466/227805614-61e9928a-d28c-4ae1-bfe1-9c8bbbc9d49b.png)
перерисовывает весь проект на клик по логотипу

2023-03-26 21:37 UTC, SergeyGlazun commented on src/redux/categories-slice.ts
>     current: {
![image](https://user-images.githubusercontent.com/70904466/227805742-a0e31da9-bbfd-473c-bce3-bd8d2d8028d4.png)
котика по больше б , а то совсем не видно ничего

2023-03-26 21:37 UTC, SergeyGlazun commented on src/redux/categories-slice.ts
>     isAmount: boolean;
![image](https://user-images.githubusercontent.com/70904466/227805811-1d239be6-d800-485a-a676-8ff5020a283c.png)
сделайте клик и по тексту тоже, самое вероятное место будет у пользователя для клика

2023-03-26 21:37 UTC, SergeyGlazun commented on src/redux/categories-slice.ts
>  }
![image](https://user-images.githubusercontent.com/70904466/227805884-b618d535-87ee-490f-9e11-5f6dbf78c0a3.png)
в бургере закрывает бургер а должен быть переход

2023-03-26 21:37 UTC, SergeyGlazun commented on src/redux/categories-slice.ts
>     isAmount: boolean;
![image](https://user-images.githubusercontent.com/70904466/227805994-1082b8a1-b431-4f5b-b4de-9baed79d5f54.png)
баг поиска. Возник после ввода в поиск  и разных переключений

2023-03-27 00:48 UTC, SergeyGlazun commented
про форму авторизации можете пропустить замечание

2023-03-27 06:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina05-04/1679897555/9-app%20-burger-menu-close-768px.png)

2023-03-27 06:30 UTC, SergeyGlazun approved these changes

2023-03-27 09:18 UTC, ValadzkoAliaksei approved these changes

2023-03-27 09:49 UTC, merged